### ISSUE TITLE
Fix Table Styling

### ISSUE THREAD

**Issue by anirudhRowjee** [HackerSpace-PESU/blog#3]
Edit the CSS to style the tables properly.
![Screenshot from 2021-07-07 08-56-35](https://user-images.githubusercontent.com/42117791/124695663-4295b180-df01-11eb-92d7-bf58568711e3.png)

It should preferably be full-width and scrollable in the event of overflow.

**Comment by shreyaskaundinya** [comment]
#7 Fix table styles

**Comment by anirudhRowjee** [comment]
this has been resolved by @shreyaskaundinya .
